export const uomTypes={
    FETCH_UOM_START:'FETCH_UOM_START',
    FETCH_UOM_SUCCESS:'FETCH_UOM_SUCCESS',
    ADD_UOM_START:'ADD_UOM_START',
    ADD_UOM_SUCCESS:'ADD_UOM_SUCCESS',
    ADD_UOM_FAILURE:'ADD_UOM_FAILURE',
    UOM_ORDER_CHANGED:'UOM_ORDER_CHANGED',
    FETCH_UOM_DETAIL:'FETCH_UOM_DETAIL',
    FETCH_UOM_DETAIL_SUCCESS:'FETCH_UOM_DETAIL_SUCCESS',
    FETCH_PERIFERAL_UOMS_START:'FETCH_PERIFERAL_UOMS_START',
    FETCH_PERIFERAL_UOMS_SUCCESS:'FETCH_PERIFERAL_UOMS_SUCCESS',
    REMOVE_UOM_START:'REMOVE_UOM_START',
    REMOVE_UOM_SUCCESS:'REMOVE_UOM_SUCCESS',
    REMOVE_UOM_FAILURE:'REMOVE_UOM_FAILURE',
    UPDATE_UOM_START:'UPDATE_UOM_START',
    UPDATE_UOM_SUCCESS:'UPDATE_UOM_SUCCESS',
    UPDATE_UOM_FAILURE:'UPDATE_UOM_FAILURE'
}