export const donationTypes={
    ADD_DONATION_ITEM:'ADD_DONATION_ITEM',
    FETCH_ORG_DETAIL_SUCCESS:'FETCH_ORG_DETAIL_SUCCESS',
    QUANTITY_CHANGED:'QUANTITY_CHANGED',
    ADD_DONATION_START:'ADD_DONATION_START',
    ADD_DONATION_SUCCESS:'ADD_DONATION_SUCCESS',
    ADD_DONATION_FAILURE:'ADD_DONATION_FAILURE',
    FETCH_DONATION_REQUEST_START:'FETCH_DONATION_REQUEST_START',
    FETCH_DONATION_REQUEST_THREAD_START:'FETCH_DONATION_REQUEST_THREAD_START',
    FETCH_DONATION_REQUEST_STATUS_START:'FETCH_DONATION_REQUEST_STATUS_START'
}