export const eventTypes={
    FETCH_EVENT_START:'FETCH_EVENT_START',
    FETCH_EVENT_SUCCESS:'FETCH_EVENT_SUCCESS',
    ADD_EVENT_START:'ADD_EVENT_START',
    ADD_EVENT_SUCCESS:'ADD_EVENT_SUCCESS',
    ADD_EVENT_FAILURE:'ADD_EVENT_FAILURE',
    FETCH_EVENT_DETAIL:'FETCH_EVENT_DETAIL',
    FETCH_EVENT_DETAIL_SUCCESS:'FETCH_EVENT_DETAIL_SUCCESS',
    FETCH_EVENT_DETAIL_FAILURE:'FETCH_EVENT_DETAIL_FAILURE',
}