export const settingTypes={
    ADD_SETTING_START:'ADD_SETTING_START',
    FETCH_SETTINGS_START:'FETCH_SETTINGS_START',
    FETCH_SETTINGS_SUCCESS:'FETCH_SETTINGS_SUCCESS',
    TOGGLE_FILTER_SUCCESS:'TOGGLE_FILTER_SUCCESS',
    TOGGLE_FILTER:'TOGGLE_FILTER'
}