export const itemTypes={
    FETCH_ITEM_START:'FETCH_ITEM_START',
    FETCH_ITEM_SUCCESS:'FETCH_ITEM_SUCCESS',
    ADD_ITEM_START:'ADD_ITEM_START',
    ADD_ITEM_SUCCESS:'ADD_ITEM_SUCCESS',
    ADD_ITEM_FAILURE:'ADD_ITEM_FAILURE',
    ITEM_ORDER_CHANGED:'ITEM_ORDER_CHANGED',
    FETCH_ITEM_DETAIL:'FETCH_ITEM_DETAIL',
    FETCH_ITEM_DETAIL_SUCCESS:'FETCH_ITEM_DETAIL_SUCCESS',
    FETCH_PERIFERAL_ITEMS_START:'FETCH_PERIFERAL_ITEMS_START',
    FETCH_PERIFERAL_ITEMS_SUCCESS:'FETCH_PERIFERAL_ITEMS_SUCCESS'
}